### ISSUE TITLE
Feedback on Milestone 1

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Income-Predictors-for-US-Adults#14]
@danielglin @Gopsathvik
Here are some remaining issues that you can focus on for the next milestone:

**About the final report**

- [x] Add figure numbers and captions to your figures. 
- [x] The text on the figures are too small.
- [x] You talk about hyper-parameter tuning for your decision tree. Elaborate on that. Did you do cross validation? If so, how? What variables did you test? What values did you consider? How did validation score improve?
- [x] I strongly believe that you should report on the training and test accuracy scores of your model. I could not see that in your report.

**About the main readme**
- [x] Add link to your report
- [x] Add instructions on how to run your analysis
- [x] Add dependencies with their version information

**Scripts:**
- [x] Add documentation to your scripts.

**Suggestions:**

- In the first sentence of the main readme, you can give the link to the whole sentence in "Income inequality in the United States is increasing source." instead of adding an extra "source" there.
- Add team member names and Github links on the main readme.

**Comment by danielglin** [comment]
Issues addressed in 60be8d311685c148ea45aa8a8d0e4be21bd1fb15
