### ISSUE TITLE
Feedback on Milestone 2

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Income-Predictors-for-US-Adults#28]
@Gopsathvik and @danielglin, great job on Milestone 2! Here are some remaining issues:

- [x] You provide a snippet of the data in the Problem Statement section. It would be better if you present that in a different format.
- [x] Some section of your table in the Features section on readme is broken which needs to be fixed.
- [x] Update the documentation at the beginning of the Makefile. As per Tiffany's instructions on this: "The Makefile must be well documented. This means comments throughout, readable code and a brief summary at the top of each file that answers who wrote it, when it was written and what it does."

**Suggestions:**

- You already have a Usage section, so you can delete the "To run the analysis, run make all from the root of the project." statement in Analysis section
- Add a dependency diagram on the readme showing the flow of your analysis and the files and scripts included in this analysis. This can go in the Workflow section on the main readme.
- Go through http://swcarpentry.github.io/make-novice/reference. This would help you make your Make code more practical. For example, you can use automatic variables and avoid some repetition.

**Comment by danielglin** [comment]
Issues addressed by 2f43e6facfb2322eb92c31f3a1e70f0a698e115c
